# Generated by Django 4.2.5 on 2023-09-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('passengers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passengergroup',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.address'),
        ),
        migrations.AddField(
            model_name='passengergroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passenger',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passengergroup'),
        ),
    ]
