# Generated by Django 4.2.5 on 2023-09-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_address_trip_destination_address_and_more'),
        ('passengers', '0003_alter_passenger_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengergroup',
            name='address',
        ),
        migrations.AddField(
            model_name='passengergroup',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_group_destination_set', to='trips.address'),
        ),
        migrations.AddField(
            model_name='passengergroup',
            name='source_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_group_source_set', to='trips.address'),
        ),
    ]
