# Generated by Django 4.2.5 on 2023-09-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_address_alter_trip_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='address',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_destination_set', to='trips.address'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_source_set', to='trips.address'),
        ),
    ]
